services:

  postgres:
    image: postgres:18.6-trixie
    container_name: finervo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finervo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout:  5s
      retries:  5

  finervo.api:
    image: finervoapi
    build:
      context: .
      dockerfile: Finervo.API/Dockerfile
    container_name: finervo-api
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: http://+:8080
      # Docker connection string using environment-provided credentials
      ConnectionStrings__Postgres: >-
        Host=postgres;Port=5432;
        Database=${POSTGRES_DB};
        Username=${POSTGRES_USER};
        Password=${POSTGRES_PASSWORD}
      # JWT secret key
      Jwt__SecretKey: ${JWT_SECRET_KEY}
    ports:
      - "8080:8080" # host:container - access via http://localhost:8080
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
